### ISSUE TITLE
When I put it in the console, it says “unexpected variable ‘if’” and “expected ; after variable declaration

### ISSUE THREAD

**Issue by Mine-Dimensions** [BlacketWare/v2#1]

**Comment by VillainsRule4000** [comment]
which script?

**Comment by Mine-Dimensions** [comment]
quickOpen.js and detailedOpen.js
Also I did openAll.js but it only opened the debug pack, not the others

**Comment by VillainsRule4000** [comment]
I don't get this error. Can you screenshot?

**Comment by Mine-Dimensions** [comment]
]
![Uploading DA789425-1BE3-492C-9DF0-71B1B01E069A.jpeg…]()

**Comment by Mine-Dimensions** [comment]
Ok maybe a bookmarklet made inspect on mobile may not work
It doesn’t work on bookmarklets right?

**Comment by VillainsRule4000** [comment]
I use the console for all testing.
