### ISSUE TITLE
?

### ISSUE THREAD

**Issue by wilsonm21** [BlacketWare/v2#1]
Hi can you make a bazaar sniper pls

**Comment by VillainsRule4000** [comment]
too overpowered
in existence but will not be published publicly

**Comment by wilsonm21** [comment]
dont you have one can we make a deal if i give you tokens or a blook you will give the script? Also wm wants to talk with you send him trade request.

**Comment by VillainsRule4000** [comment]
> dont you have one

yes

> can we make a deal if i give you tokens or a blook you will give the script?

no; nobody has the tokens I would charge
i have all blooks

> Also wm wants to talk with you send him trade request.

no.
im never talking to wm again.

**Comment by wilsonm21** [comment]
bro wm said to tell you he just wants to be cool

**Comment by VillainsRule4000** [comment]
> bro wm said to tell you he just wants to be cool

ok, tell yourself [wm] (im not dumb) that won't happen.
you've been blocked from posting on BlacketWare.
