### ISSUE TITLE
Can you unban me from blacket acai banned me

### ISSUE THREAD

**Issue by ThePineappleMan2013** [BlacketWare/v2#3]
Can you unban me from blacket acai banned me

**Comment by VillainsRule4000** [comment]
I am not a mod and this is not a Blacket helpline.
DM Xotic#0001 on Discord to appeal bans.

**Comment by ThePineappleMan2013** [comment]
how do you DM pepole
________________________________

**Comment by VillainsRule4000** [comment]
> how do you DM pepole

Were you born in 2013?

**Comment by ThePineappleMan2013** [comment]
yes
i was born 2013
________________________________

**Comment by VillainsRule4000** [comment]
> yes i was born 2013

You must be over 13 years of age to be on Github. You have been blocked on BlacketWare.
