### ISSUE TITLE
WTF

### ISSUE THREAD

**Issue by bentyyyyy** [BlacketWare/v2#3]
WHATS HAPPING WITH BLACHET HUHHHHH!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by VillainsRule4000** [comment]
hundreds of people want v2
it's crashing
https://discord.gg/blacket for more info

**Comment by bentyyyyy** [comment]
oh thank you for understanding what website is it gunna be on

**Comment by bentyyyyy** [comment]
im on shool chrom book i cant go on discord its blocked

**Comment by bentyyyyy** [comment]
BRO IM UPSET but its ok bc i know that its gunna be up by tomoorryyyyy hopifully
