### ISSUE TITLE
question

### ISSUE THREAD

**Issue by addasdasdasdasdasd** [BlacketWare/v2#6]
i am guessing not but is it possible for add exp?

**Comment by addasdasdasdasdasd** [comment]
stupid question im not sure if this is even possible though

**Comment by VillainsRule4000** [comment]
you get exp from opening boxes, just spam cheap ones ig
but no, a direct exp hack without a cost isn't possible

**Comment by addasdasdasdasdasd** [comment]
so it is with money??

**Comment by VillainsRule4000** [comment]
> so it is with money??

when you open a pack (with tokens, yes) you pull a blook.
the rarer the blook, the more exp you get.
